# _run_analysis.R
#
# This code was generated by Gemini on 2025-07-08 as a fork of the
# original repo at https://example.com/example_analysis
#
# This script serves as the main entry point to reproduce the original
# analysis. It sources functions from the R/ directory, loads the original
# user data, runs the analysis, and saves the outputs.

# 1. SETUP ----
# Ensure required packages are installed
if (!require("here")) install.packages("here")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("dplyr")) install.packages("dplyr")

library(here)
library(ggplot2)
library(dplyr)

# Source all functions from the R/ directory
lapply(list.files(here("R"), pattern = "\\.R$", full.names = TRUE), source)

# 2. CONFIGURATION ----
# Define file paths using the here() package for robustness.
# These paths point to the original data and desired output locations.
# EDITED: station_info_path <- here("data", "station_info.csv")
# EDITED: catch_data_path <- here("data", "catch_data.csv")
station_info_path <- here("inst", "extdata", "station_info.csv")
catch_data_path <- here("inst", "extdata", "catch_data.csv")
output_dir <- here("outputs")
predictions_output_path <- here(output_dir, "model_predictions.csv")
plot_output_path <- here(output_dir, "abundance_plot.png")

# Define species for analysis
species_list <- c(
  "Red Snapper" = "Lutjanus campechanus",
  "Gag Grouper" = "Mycteroperca microlepis"
)

# 3. DATA LOADING AND PREPARATION ----
# Load station info
station_info <- read.csv(station_info_path)

# Load catch data (assumes no header as in original script)
catch_data <- load_catch_data(
  filepath = catch_data_path,
  col_names = c("station_id", "species_name", "catch_count")
)

# Merge and calculate densities
# This step reproduces the logic from the original script, including the
# potentially incorrect unit conversion (see debrief.md, Issue 4.1).
analysis_data <- calculate_densities(
  station_df = station_info,
  catch_df = catch_data
)

# 4. MODELING AND PREDICTION ----
# Run models and generate predictions for each species in a loop
all_predictions <- lapply(names(species_list), function(species_common_name) {
  
  species_scientific_name <- species_list[[species_common_name]]
  
  # Filter data for the current species
  species_data <- analysis_data[analysis_data$species_name == species_scientific_name, ]
  
  # Fit the Poisson GLM
  species_model <- fit_species_model(
    species_df = species_data,
    formula = catch_count ~ bottom_temp_c
  )
  
  # Print model summary to console, as in original script
  cat(paste("---\n", species_common_name, "Model Summary\n---\n"))
  print(summary(species_model))
  
  # Generate predictions
  predictions_df <- generate_predictions(
    model = species_model,
    species_df = species_data,
    species_name = species_scientific_name,
    temp_var = "bottom_temp_c"
  )
  
  return(predictions_df)
})

# Combine all species predictions into a single data frame
final_predictions <- bind_rows(all_predictions)

# 5. VISUALIZATION ----
# Create the abundance plot
abundance_plot <- plot_abundance_trends(
  plot_data = analysis_data,
  predictions = final_predictions,
  species_map = species_list
)

# 6. SAVE OUTPUTS ----
# Create output directory if it doesn't exist
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

# Save predictions to CSV
write.csv(final_predictions, predictions_output_path, row.names = FALSE)

# Save plot to PNG
ggsave(
  filename = plot_output_path,
  plot = abundance_plot,
  width = 8,
  height = 6,
  dpi = 100
)

print(paste("Analysis complete. Outputs are in the '", output_dir, "' directory."))

