# R/01_data_processing_functions.R
#
# This code was generated by Gemini on 2025-07-08 as a fork of the
# original repo at https://example.com/example_analysis
#
# Contains functions related to loading and processing raw data.

#' Load Catch Data
#'
#' Reads a CSV file, assuming it has no header, and assigns specified column
#' names.
#'
#' @param filepath character. The full path to the input CSV file.
#' @param col_names character vector. The column names to assign to the data.
#'
#' @return A data.frame with the loaded data and assigned column names.
load_catch_data <- function(filepath, col_names) {
  stopifnot(is.character(filepath), length(filepath) == 1)
  stopifnot(is.character(col_names))

  catch_data <- read.csv(filepath, header = FALSE)
  colnames(catch_data) <- col_names
  return(catch_data)
}


#' Calculate Catch Densities
#'
#' Merges station and catch data, calculates catch density per square kilometer,
#' filters for finite values, and converts density to per square mile.
#'
#' @details **Warning:** This function deliberately reproduces a potential bug
#'   from the original script. The conversion from km^2 to mi^2 uses a linear
#'   factor, not an area factor. See `debrief.md` for details.
#'
#' @param station_df A data.frame with station information, including columns
#'   `station_id` and `area_swept_km2`.
#' @param catch_df A data.frame with catch data, including columns
#'   `station_id` and `catch_count`.
#'
#' @return A data.frame containing the merged data with new density columns.
calculate_densities <- function(station_df, catch_df) {
  # Input validation
  stopifnot(
    is.data.frame(station_df),
    all(c("station_id", "area_swept_km2") %in% names(station_df))
  )
  stopifnot(
    is.data.frame(catch_df),
    all(c("station_id", "catch_count") %in% names(catch_df))
  )

  merged_data <- merge(station_df, catch_df, by = "station_id")

  # Calculate density per km2
  merged_data$density_per_km2 <- merged_data$catch_count / merged_data$area_swept_km2

  # Filter out rows with non-finite density values (e.g., from division by zero)
  merged_data <- merged_data[is.finite(merged_data$density_per_km2), ]

  # Convert density to square miles (REPRODUCING ORIGINAL LOGIC)
  conversion_factor_km2_to_mi2 <- 0.62
  merged_data$density_per_sq_mi <- merged_data$density_per_km2 / conversion_factor_km2_to_mi2

  return(merged_data)
}

