# R/02_analysis_functions.R
#
# This code was generated by Gemini on 2025-07-08 as a fork of the
# original repo at https://example.com/example_analysis
#
# Contains functions related to statistical modeling and prediction.

#' Fit Species Abundance Model
#'
#' Fits a Generalized Linear Model (GLM) with a Poisson family for a given
#' species' data.
#'
#' @param species_df A data.frame filtered for a single species. Must contain
#'   the variables specified in the `formula`.
#' @param formula A formula object for the GLM (e.g., `catch_count ~ bottom_temp_c`).
#'
#' @return A `glm` model object.
fit_species_model <- function(species_df, formula) {
  stopifnot(is.data.frame(species_df))
  stopifnot(inherits(formula, "formula"))

  model <- glm(formula, data = species_df, family = poisson)
  return(model)
}


#' Generate Model Predictions
#'
#' Creates a data frame of predictions from a fitted model over a range of
#' temperatures.
#'
#' @param model A fitted `glm` model object.
#' @param species_df A data.frame for a single species, used to determine the
#'   range of the temperature variable. Must contain the `temp_var` column.
#' @param species_name The scientific name of the species for labeling.
#' @param temp_var The name of the temperature variable (character string).
#'
#' @return A data.frame with columns `species`, `temperature`, and
#'   `predicted_count`.
generate_predictions <- function(model, species_df, species_name, temp_var = "bottom_temp_c") {
  stopifnot(inherits(model, "glm"))
  stopifnot(is.data.frame(species_df))
  stopifnot(temp_var %in% names(species_df))
  stopifnot(is.character(species_name))

  # Create a sequence of new temperatures for prediction
  min_temp <- min(species_df[[temp_var]], na.rm = TRUE)
  max_temp <- max(species_df[[temp_var]], na.rm = TRUE)
  new_temps <- data.frame(
    bottom_temp_c = seq(min_temp, max_temp, length.out = 100)
  )
  
  # Predict new values
  predicted_counts <- predict(model, newdata = new_temps, type = "response")
  
  # Create the final predictions data frame
  predictions_df <- data.frame(
    species = species_name,
    temperature = new_temps[[temp_var]],
    predicted_count = predicted_counts
  )

  return(predictions_df)
}

