# R/03_visualization_functions.R
#
# This code was generated by Gemini on 2025-07-08 as a fork of the
# original repo at https://example.com/example_analysis
#
# Contains functions related to creating plots and other visualizations.

#' Plot Abundance vs. Temperature Trends
#'
#' Creates a scatter plot of catch count vs. bottom temperature, overlaid with
#' fitted model prediction lines. This function uses ggplot2 to faithfully
#' reproduce the appearance of the original base R plot.
#'
#' @param plot_data A data.frame containing the raw data for plotting. Must
#'   include `bottom_temp_c`, `catch_count`, and `species_name`.
#' @param predictions A data.frame containing the model predictions. Must
#'   include `temperature`, `predicted_count`, and `species`.
#' @param species_map A named character vector mapping scientific names (values)
#'   to common names (names). E.g., `c("Red Snapper" = "L. campechanus")`.
#'
#' @return A `ggplot` object.
plot_abundance_trends <- function(plot_data, predictions, species_map) {
  stopifnot(is.data.frame(plot_data))
  stopifnot(is.data.frame(predictions))
  stopifnot(is.character(species_map), !is.null(names(species_map)))

  # Define colors to match the original plot's implicit color scheme
  # Base R sorts factor levels alphabetically: Gag Grouper, Red Snapper
  # Original plot used col=as.factor(), so Gag Grouper is black (1), Red Snapper is red (2)
  # We must manually assign colors to match this.
  species_colors <- c(
    "Mycteroperca microlepis" = "black", # Gag Grouper
    "Lutjanus campechanus" = "red"      # Red Snapper
  )
  
  # The original plot used black and red lines. We need to map these
  # to the species correctly.
  line_colors <- c(
    "Lutjanus campechanus" = "black", # RS Model Fit
    "Mycteroperca microlepis" = "red" # GG Model Fit
  )

  p <- ggplot(plot_data, aes(x = bottom_temp_c, y = catch_count)) +
    # Scatter plot points
    geom_point(aes(color = species_name), shape = 19, size = 2.5) +
    # Model prediction lines
    geom_line(
      data = predictions,
      aes(x = temperature, y = predicted_count, color = species),
      linewidth = 1
    ) +
    # Apply manual color scales to match the original plot
    scale_color_manual(
      name = "Species",
      values = species_colors,
      labels = names(species_map)
    ) +
    # This is a trick to get the lines colored differently in the legend
    # We map the 'linetype' aesthetic to the species name
    scale_linetype_manual(
      name = "Model Fit",
      values = c("solid", "solid"),
      labels = paste(names(species_map), "Fit")
    ) +
    # Labels and Title
    labs(
      x = "Bottom Temperature (°C)",
      y = "Catch Count",
      title = "Fish Abundance vs. Bottom Temperature"
    ) +
    # Classic theme to resemble base R plot
    theme_classic() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = c(0.85, 0.85), # Approximate position
      legend.background = element_rect(fill = "white", color = "black")
    )

  # To get the legend exactly right, we override the aesthetics.
  # This is complex but necessary to match the base R plot's legend.
  p <- p + guides(
    color = guide_legend(
      title = "Legend",
      override.aes = list(
        shape = c(19, 19),
        # Colors in legend: GG (black), RS (red)
        color = c("black", "red")
      )
    ),
    linetype = guide_legend(
      title = "Legend",
      override.aes = list(
        # Line colors in legend: RS fit (black), GG fit (red)
        color = c("black", "red")
      )
    )
  )

  return(p)
}

